### ISSUE TITLE
[Umbrella] Update issue bugs

### ISSUE THREAD

**Issue by justaugustus** [uwu-tools/gh-jira-issue-sync#50]
Progress tracker for fixing bugs around issue updates

- [ ] Update operations fail because fields cannot be set: https://github.com/uwu-tools/gh-jira-issue-sync/issues/30
- [ ] Issue creation fails with generic message: https://github.com/uwu-tools/gh-jira-issue-sync/issues/10
- [ ] Comment regular expression is fragile: https://github.com/uwu-tools/gh-jira-issue-sync/issues/9
- [ ] When updating issues, only first 50 Jira issues are considered: https://github.com/uwu-tools/gh-jira-issue-sync/issues/8
